### ISSUE TITLE
Source script fails to retrieve credentials values

### ISSUE THREAD

**Issue by samirakhelifi** [pharriso/ansible_constructed_inventory#1]
Hello Mr.Harrison,
first of all thank you for your blog "Ansible Constructed Inventory Plugin". Actually, i wanted to create dynamic inventory (that will contain dynamic groups) from GLPI so i used two plugins: "Ansible dynamic inventory for GLPI" customized plugin to retrieve infomation from GLPI and constructed plugin to create dynamic groups as you recommended, it does work properly in AWX but when i tried to use AWX credential management i'm always having the error indicating that he couldn't parse the variables:

Input configuration:
````
fields:
  - id: url
    type: string
    label: url
  - id: apptoken
    type: string
    label: apptoken
    secret: true
  - id: usertoken
    type: string
    label: usertoken
    secret: true
required:
  - apptoken
  - usertoken
  - url
 ````

Injector configuration:
````
env:
    GLPI_URL: '{{ url }}'
    GLPI_APPTOKEN: '{{ apptoken }}'
    GLPI_USERTOKEN: '{{ usertoken }}'

````

source file glpi.yml:
````
plugin: unistra.glpi.inv
glpi_url: "{{ GLPI_URL }}"
glpi_apptoken:  "{{ GLPI_APPTOKEN }}"
glpi_usertoken: "{{ GLPI_USERTOKEN }}"
glpi_verify_certs: False
glpi_use_headers: True
queries:
  #
  # Servers by system
  #
  glpi-non-prod-all-hosts:
    itemtype: Computer
    fields:
    - 1   # name
    - 4   # ComputerType.name
    - 31  # State.completename
    criteria:
    - { link: AND, field: 31, searchtype: contains, value: '^EN SERVICE$' }
    hostname: $1
    hostvars:
      computertype: $4
      state: $31
````
and i've created credentails and put the values as shown:

<img width="755" alt="glpi_credentials" src="https://github.com/pharriso/ansible_constructed_inventory/assets/67977540/28485c5e-03bb-4964-a1d9-bfaeaa289f5a">

and i've configured the source with the target credentials:

<img width="472" alt="source credentials" src="https://github.com/pharriso/ansible_constructed_inventory/assets/67977540/3401295a-31bc-4409-a49b-d90e4347a822">

but i'm always getting this error message :

<img width="616" alt="source-error" src="https://github.com/pharriso/ansible_constructed_inventory/assets/67977540/972698fb-2e76-4e7f-8d46-75e89f0f3420">

Also when i tried to remove these three lines from my source script as you recommended :

<glpi_url: "{{ GLPI_URL }}"
glpi_apptoken:  "{{ GLPI_APPTOKEN }}"
glpi_usertoken: "{{ GLPI_USERTOKEN }}" >

 => I'm almost getting the same error that he can't find glpi access details.
